name: flutter_tutorial
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: "^0.4.2"
  map_view: "^0.0.14"
  google_maps_webservice: "^0.0.6"
  location: "^1.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/sample1.jpg
    - images/sample2.jpg
